// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAesg_AsmGcFZpL_wYjskG_x7UvQhY0dRY',
    appId: '1:104265584311:web:4c622814962d2b4141c732',
    messagingSenderId: '104265584311',
    projectId: 'nota-ai-tool',
    authDomain: 'nota-ai-tool.firebaseapp.com',
    storageBucket: 'nota-ai-tool.appspot.com',
    measurementId: 'G-ME3B62SDTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfSh83LIFbCLO1G0f7cI7Y4AIpKZ1TemA',
    appId: '1:104265584311:android:fbfdc01a655b5aa541c732',
    messagingSenderId: '104265584311',
    projectId: 'nota-ai-tool',
    storageBucket: 'nota-ai-tool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJCDFrcYpDzthOg4r533FOkYx5NjjytQ8',
    appId: '1:104265584311:ios:3cb4f5e94d33abc341c732',
    messagingSenderId: '104265584311',
    projectId: 'nota-ai-tool',
    storageBucket: 'nota-ai-tool.appspot.com',
    iosBundleId: 'com.example.todoaiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJCDFrcYpDzthOg4r533FOkYx5NjjytQ8',
    appId: '1:104265584311:ios:cd93bedf9fbc608541c732',
    messagingSenderId: '104265584311',
    projectId: 'nota-ai-tool',
    storageBucket: 'nota-ai-tool.appspot.com',
    iosBundleId: 'com.example.todoaiapp.RunnerTests',
  );
}
